### ISSUE TITLE
promexample_mesmer_zio_forwarded_null in prometheus

### ISSUE THREAD

**Issue by lgajowy** [ScalaConsultants/mesmer#538]
It seems that some metrics in result of tagging loose their name and we set it to null which results in a metric named as in title. This needs to be fixed

**Comment by mBut** [comment]
@lgajowy previously we discussed that it might be reasonable to make an Advice for each ZIO Metric method that creates a new metrics instance: `contramap`, `map`, `mapType` and `taggedWith`. Based on that, initially I made a wrong assumption that for all these mapping functions generic Advice can be used with shared `VirtualField` registration logic. This change worked for `contramap` and the bug has been fixed. However other mapping functions have different behaviour and might require extra investigation to address it right. 

For example in the `map` method (is also called inside `taggedWith` body), the provided function is evaluated only on `value` method access, which is called by OT callback. So that if we only modify `map` method body, this seem to register wrong references to the metric object, so that at the time when OT callback is called it is not clear what metric instance it applies to. 
 
```
  final def map[Out2](f: Out => Out2): Metric[Type, In, Out2] =
    new Metric[Type, In, Out2] {
      val keyType = self.keyType

      override private[zio] val unsafe: UnsafeAPI =
        new UnsafeAPI {
          override def update(in: In, extraTags: Set[MetricLabel])(implicit unsafe: Unsafe): Unit =
            self.unsafe.update(in, extraTags)

          override def value(extraTags: Set[MetricLabel])(implicit unsafe: Unsafe): Out2 =
            f(self.unsafe.value(extraTags))

          override def modify(in: In, extraTags: Set[MetricLabel])(implicit unsafe: Unsafe): Unit =
            self.unsafe.modify(in, extraTags)
        }
    }
```

Possible solution can be avoid modifying `map` constructor method to ensure `VirtualField` references correctness and instead make sure that context around the `f: Out => Out2` call is correct. 

I'd suggest to create a new ticket and evaluate it separately rather to try to fix it as part of the current bug. Lukasz, what do you think?

**Comment by lgajowy** [comment]
That's indeed a separate issue - I agree. 

Just some loose bunch of bytebuddy utils:

- @Advice.Origin("#m") will get you the name of the caller method. That could be useful when it comes to instrumenting all these zio methods
- we can also instrument the Metric's constructors (not only regular methods). Not sure how helpful it is in this case. Maybe there's a way of providing the metric name and attributes to the VitrtualField during construction? That's something I was unable to do then, but maybe I missed something...
