### ISSUE TITLE
Add missing Advice templates for ZIO Metrics mapping functions

### ISSUE THREAD

**Issue by mBut** [ScalaConsultants/mesmer#629]
This issues is a follow up of #538

`zio.metrics.Metric` class implements number of mapping methods, which create a new copy of the metric instance when invoked. This makes a new metric instance to replace the old one, which in turn is garbage collected. This breaks the `VirtualField` references at invocation time. The methods are `map`, `mapType` and `taggedWith`. We need to ensure that `VirtualField` correctly tracks references when these methods are called. We also need to keep in mind that the provided mapping functions can be merely constructors and actual reference of virtual field stored values can be done in callbacks at later point of time. 

You can find more details in [this comment](https://github.com/ScalaConsultants/mesmer/issues/538#issuecomment-1453679693)

**Comment by ptrdom** [comment]
I created an issue in ZIO repository in regards to how we should better approach integrating ZIO metrics with OTEL - https://github.com/zio/zio/issues/7897. Let's take into account the outcome of this issue when designing our improved implementation.

And just to summarize our discussion in Slack, it seems that the better approach is to interact with ZIO's `ConcurrentMetricRegistry`, rather than instrumenting ZIO's `Metric` instances directly.

**Comment by lgajowy** [comment]
no longer an issue with the new implementation of ZIO metrics
